### PR TITLE
Bring back exiv2 anitya

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by Justinzobel** [comment]
```
-- Could NOT find inih (missing: inih_LIBRARY inih_INCLUDE_DIR) 
CMake Error at cmake/Findinih.cmake:28 (message):
  inih library not found
  ```
  Not found in exiv build.

**Comment by travier** [comment]
We can disable it like we did for another app I don't remember.

**Comment by travier** [comment]
https://github.com/flathub/org.gimp.GIMP/blob/6acd6e001967f0934dade222ddadc1f26585a0be/org.gimp.GIMP.json#L319

**Comment by travier** [comment]
Let's remove the inih dependency instead? It's not used for the library, only for a command line tool that we don't use.

**Comment by tsdgeos** [comment]
> Let's remove the inih dependency instead? It's not used for the library, only for a command line tool that we don't use.

Grepping in the code shows it's used in readExiv2Config which is used in places like CanonMakerNote::printCsLensType, which then i have a bit of trouble tracking where it's used but doesn't seem obvious is for the command line tool only

Is there some docu or something that says inih is only for the command line tool?

**Comment by travier** [comment]
https://exiv2.org/manpage.html#config_file

**Comment by travier** [comment]
https://github.com/flathub/org.gimp.GIMP/commit/4335a0912ccfd53e173703926aabbdafbcf3345f

**Comment by tsdgeos** [comment]
I'm honestly not convinced :D

Does it hurt us to actually provide the dependencies the library wants?

**Comment by Erick555** [comment]
It's yet another point of possible failure. Especially when relying on github-generated tarballs.

**Comment by tsdgeos** [comment]
I don't remember a single problem with github tarballs in all the hundred flathub apps we have, can you point to a place such a problem happened?

**Review by travier — APPROVED** [review]
I'm fine with both. If you prefer to add it let's do it. I don't think it matters much here.

**Comment by Erick555** [comment]
> I don't remember a single problem with github tarballs in all the hundred flathub apps we have, can you point to a place such a problem happened?

Perhaps you weren't paying attention to the [worldwide news](https://lwn.net/Articles/921787/). Note the difference between github auto-generated tarballs and upstream generated tarballs on github. The problem is with the former.

**Pull request merged**
