### PR TITLE
Fix accesing embedded files

### PR DESCRIPTION
**Pull request by Erick555**
Fixes https://github.com/flathub/org.kde.okular/issues/62

### CODE REVIEW

**Comment by aleixpol** [comment]
Why would this solve the issue? internal okular instances should share a /tmp.

**Comment by Erick555** [comment]
@aleixpol Embedded files are opened externally through portal.

**Comment by Erick555** [comment]
I confirmed this working.

**Comment by Erick555** [comment]
@aleixpol ping

**Comment by Erick555** [comment]
@aleixpol could you merge this one?

**Comment by TingPing** [comment]
> Why would this solve the issue? internal okular instances should share a /tmp.

`/tmp` is a non-shared tmpfs in flatpak, so thats not useful.

**Comment by grulja** [comment]
See my comment https://github.com/flathub/org.kde.okular/issues/62#issuecomment-613270351. I think that it is a better approach.

@aleixpol at the time when you ask the portal to open a file, it doesn't know it will be opened in Okular and both sides, like the portal and the app itself (first Okular instance) need to have access to this file to open it so it needs to be placed into location where both have access, which can be either /tmp (system one, not the sandboxed one) or it can be the application cache, which is available outside as well and for each app it's in $HOME/.var/app/app_name/cache.

**Comment by Erick555** [comment]
@grulja I [proposed this before](https://github.com/flathub/org.kde.okular/pull/66) but for some reason it didn't work (could be a flatpak bug).

**Comment by eszlari** [comment]
fixed in https://github.com/flathub/org.kde.okular/pull/66

**Pull request closed without merging**
