### PR TITLE
Add --socket=cups for printing support

### PR DESCRIPTION
**Pull request by grulja**
This will magically allow to print with Flatpak 1.6 (once released).

### CODE REVIEW

**Comment by grulja** [comment]
Ok, looks we have to wait for Flatpak 1.6 to be updated in Flathub.

**Comment by grulja** [comment]
bot, build

**Comment by tsdgeos** [comment]
@grulja does this mean it will also need the flatpak client to be 1.6?

**Comment by grulja** [comment]
> @grulja does this mean it will also need the flatpak client to be 1.6?
No,  I was told that recent (~2 years old) Flatpak versions will just ignore it.

**Comment by tsdgeos** [comment]
I guess we can merge it then? (if it works, i have not tried it)

**Comment by grulja** [comment]
> I guess we can merge it then? (if it works, i have not tried it)

It works, I tested this change with Okular and Kate.

**Comment by grulja** [comment]
Albert, can you merge this then?

**Comment by tsdgeos** [comment]
Sorry i thought you could merge stuff.

**Comment by barthalion** [comment]
@tsdgeos Does it make sense if I create KDE team under Flathub org and grant you folks write permissions to all KDE apps?

**Comment by tsdgeos** [comment]
Yes, that would make sense i guess.

Otherwise i'm not sure if there's an easy way to know who has access to commit under the various random org.kde.xxx repos (maybe there is, i'm not a heavy github user)

**Comment by barthalion** [comment]
Done, please make sure to accept the invite to organization.

**Pull request merged**
