### PR TITLE
Remove unused dependencies

### PR DESCRIPTION
**Pull request by Erick555**
CHM file are no longer supported:

https://github.com/flathub/org.kde.okular/issues/372

https://invent.kde.org/graphics/okular/-/merge_requests/968

### CODE REVIEW

**Review by travier — APPROVED** [review]

**Comment by tsdgeos** [comment]
You need to remove chm from okular-mimetypes.patch too

**Comment by Erick555** [comment]
done

**Comment by tsdgeos** [comment]
Can i convince you to do the same for https://github.com/flathub/org.kde.okular.kirigami/ ?

**Comment by Erick555** [comment]
https://github.com/flathub/org.kde.okular.kirigami/pull/11

**Pull request merged**
